/** `DEFAULT.MODULE.COMPONENT.SETTING` */
export const DEFAULT = {
  CARDS: {
    GALLERY_CARD: {
      DATE_ZOOM_INDEX: 0,
      DETAILS_ZOOM_INDEX: 0,
      DETAILS_MAX_LINES: 3,
      ENABLED: true,
      FILE_SIZE_ZOOM_INDEX: -1,
      IMAGE_COLLECTION_ICON_ZOOM_INDEX: -1,
      IMAGE_COUNT: 0,
      ORGANIZED_ZOOM_INDEX: 0,
      PERFORMER_LIST_ZOOM_INDEX: 0,
      PHOTOGRAPHER_ZOOM_INDEX: -1,
      RATING_BANNER_ZOOM_INDEX: 0,
      RATING_ICON_ZOOM_INDEX: -1,
      STUDIO_ZOOM_INDEX: 0,
      THUMBNAIL_BACKGROUND_IMAGE: false,
      THUMBNAIL_BACKGROUND_STYLE: null,
      ZIP_ICON_ZOOM_INDEX: -1,
    },
    SCENE_CARD: {
      AUDIO_CODEX_ZOOM_INDEX: -1,
      ASPECT_RATIO_ZOOM_INDEX: -1,
      BIT_RATE_ZOOM_INDEX: -1,
      DATE_ZOOM_INDEX: 0,
      DETAILS_ZOOM_INDEX: 0,
      DETAILS_MAX_LINES: 3,
      DIRECTOR_ZOOM_INDEX: -1,
      DURATION_ZOOM_INDEX: 0,
      ENABLED: true,
      FILE_SIZE_ZOOM_INDEX: -1,
      FRAME_RATE_ZOOM_INDEX: -1,
      INTERACTIVE: -1,
      O_COUNT_ZOOM_INDEX: -1,
      ORGANIZED_ZOOM_INDEX: 0,
      PERFORMER_LIST_ZOOM_INDEX: 0,
      PLAY_COUNT_ZOOM_INDEX: -1,
      PREVIEWS_ENABLED: true,
      RATING_BANNER_ZOOM_INDEX: 0,
      RATING_ICON_ZOOM_INDEX: -1,
      RESOLUTION_AS_ICON: false,
      RESOLUTION_ZOOM_INDEX: 0,
      STUDIO_ZOOM_INDEX: 0,
      THUMBNAIL_BACKGROUND_IMAGE: false,
      THUMBNAIL_BACKGROUND_STYLE: null,
      VIDEO_CODEX_ZOOM_INDEX: -1,
    },
    SHARED: {
      ENABLE_FOOTER_BUTTON_COUNTS: true,
      TIMESTAMP_PADDING: false,
    },
  },
  GENERAL: {
    LOCALE_DATE_FORMAT: false,
  },
} as const;

export const PLUGIN = {
  ID: "valkyr-ui",
} as const;

export const ROUTE = {
  INDEX: "/plugins/valkyr-ui",
} as const;
